service: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        # arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionsTable
        - ${self:custom.AuctionsTable.arn}

# cloudformation code for dynamodb
resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

# we define here AttributeDefinitions, without keySchema dynamoDb doesn't know what to da

  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  AuctionsTable: 
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn

  bundle:
    linting: false